version: '3.9'

services:
  # Сервис для разворачивания контейнера с базой данных
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password


  # Сервис для разворачивания контейнера с приложением
  webapi:
    build:
      context: .
    ports:
      - "8080:8084"
    depends_on:
      - database
    env_file:
      - src/docker.env
    environment:
      - PYTHONUNBUFFERED=0
    command: bash -c "alembic upgrade head && python3.10 -m src"

  # Сервис для разворачивания контейнера с автотестами
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:8084
      STAGE: all

