"""change column name

Revision ID: f8aa55901b87
Revises: f27965be2c8e
Create Date: 2023-03-07 19:37:34.176949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8aa55901b87'
down_revision = 'f27965be2c8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True))
    op.add_column('animals', sa.Column('life_status', sa.Enum('ALIVE', 'DEAD', name='lifestatus'), nullable=True))
    op.add_column('animals', sa.Column('death_datetime', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('animals', 'dead_datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('dead_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('animals', 'death_datetime')
    op.drop_column('animals', 'life_status')
    op.drop_column('animals', 'gender')
    # ### end Alembic commands ###
